sudo: false
language: go

before_install:
  - go get -t -v ./...
install:
  - go install ./cmd/migratego
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go test -v -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
script:
  - go test ./...

go:
  - 1.7
  - 1.8
  - tip